### PR TITLE
PLUGINRANGERS-2148 | Changed log path to wp-content/uploads folder

### PR DESCRIPTION
**Pull request by davidmolinacano**
Required by:

- https://github.com/doofinder/support/issues/2148

### CODE REVIEW

**Review by sofia-doofinder — APPROVED** [review]

**Review by pedromcp90 — CHANGES_REQUESTED** [review]
Good job, but I think we should create a `.htaccess` file to prevent someone accessing and downloading these files.

**Review by eduardogomez97 — COMMENTED** [review]
Now that this change is going to be made, it might be interesting to increase a little the security of the logs. Currently they are fully accessible because they do not contain any sensitive data. But security could be increased taking into account how it can also affect support.

Good work!

**Review by eduardogomez97 — APPROVED** [review]

**Comment by sofia-doofinder** [comment]
en otros plugins como prestashop los logs están accesibles si escribes la ruta en el navegador...

**Comment by davidmolinacano** [comment]
I've added a small security improvement by adding .htaccess and index.php via `file_put_contents` @pedromcp90

**Review by pedromcp90 — APPROVED** [review]
Awesome! :1st_place_medal:

**Review by sofia-doofinder — APPROVED** [review]

**Pull request merged**
